### ISSUE TITLE
disable gnome keyboard

### ISSUE THREAD

**Issue by benslice** [UshakovVasilii/gnome-shell-extension-florence-indicator#2]
Question and related feature request. 

I love florence, but I cannot find a way to disable the default gnome-shell on-screen keyboard! Every time I click on a terminal with the touch screen it comes up.

Question: Do you know how I can disable it. I see a number of suggestions on forums, but many are quite dated and none really work.

Feature request: I Do like having the default onscreen keyboard on the lock screen, or when I log in (before florence is running). It would be nice if florence could disable the gnome keyboard while it is running, and perhaps turn it off again when it exits. Or provide a way to toggle it in the bar. 

(There is a way to toggle it in the accessibility menu, but for me it has no effect.)

**Comment by UshakovVasilii** [comment]
Hi, I'm sorry for late reply.
>  Do you know how I can disable it. I see a number of suggestions on forums, but many are quite dated and none really work.

As I understand it is: 
Settings => Universal Access => Screen Keyboard (Typing)

> Feature request: ...

I want it too :-) , but I have not idea how implement this for now

Thanks
